# 默认True（开启），设为False来关闭此选项
# 作用：是否使用二维码登录
qrcodeLogin: True

# 默认False（开启），设为True来关闭此选项
# 作用：用于控制是否显示座位价钱，关闭此选项可以极大的节省获取车次信息的时间
priceView: False

# 默认False（开启），设为True来开启此选项
# 作用：开发者调式选项，开启此选项将输出更多细节，建议普通用户关闭
debug: False

# 作用：当关闭二维码登录时，您的账号
userName:

# 作用：当关闭二维码登录时，您的密码
userPassword: